# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'TimeIn.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import cv2

from PyQt5.QtWidgets import QWidget, QVBoxLayout, QGridLayout, QPushButton, QLineEdit
from PyQt5.QtWidgets import *
from PyQt5 import QtCore, QtGui, QtWidgets


class TimeIn(QtWidgets.QFrame):
    
    def __init__(self):
        super().__init__()
        
        self.setObjectName("Time In")
        self.resize(822, 519)
        
        # set up facial detection 
        self.face_detector = cv2.CascadeClassifier(cv2.data.haarcascades + 'haarcascade_frontalface_default.xml')
        
        # Video
        self.label = QtWidgets.QLabel(self)
        self.label.setGeometry(QtCore.QRect(30, 20, 571, 481))
        self.label.setObjectName("label")
        
        # Register Button
        self.pushButton = QtWidgets.QPushButton(self)
        self.pushButton.setGeometry(QtCore.QRect(630, 180, 151, 41))
        self.pushButton.setObjectName("pushButton")
        
        # Switch Camera
        self.pushButton_2 = QtWidgets.QPushButton(self)
        self.pushButton_2.setGeometry(QtCore.QRect(630, 230, 151, 41))
        self.pushButton_2.setObjectName("pushButton_2")
        
        # to start video streaming
        self.videoStream = cv2.VideoCapture(0)
        self.videoStream.set(4, 1080)
        
        self.timer = QtCore.QTimer(self)
        self.timer.timeout.connect(self.videoStreaming)
        self.timer.start(30)

        self.retranslateUi()
        QtCore.QMetaObject.connectSlotsByName(self)
        
    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("Frame", "Frame"))
        self.label.setText(_translate("Frame", "TextLabel"))
        self.pushButton.setText(_translate("Frame", "Register "))
        self.pushButton_2.setText(_translate("Frame", "Switch Camera"))

    def videoStreaming(self):
        ret, frame = self.videoStream.read()
        
        # if no detected frames
        if not ret:
            self.label.setText("Please wait camera is loading")
            return
        
        frame = cv2.flip(frame, 1)
        
        gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
                
        # load facial detection
        faces = self.face_detector.detectMultiScale(gray,
                                                    scaleFactor=1.1,
                                                    minNeighbors=20,
                                                    minSize=(180, 180),
                                                    flags=cv2.CASCADE_SCALE_IMAGE)
        
        for (x, y, w, h) in faces:      
            cv2.rectangle(frame, (x, y), (x+w, y+h), (0,255,0), 2)
        
        # display the frame on the label
        height, width, channel = frame.shape
        bytesPerLine = channel * width
        qImg = QtGui.QImage(frame.data, width, height, bytesPerLine, QtGui.QImage.Format_BGR888)
        pixmap = QtGui.QPixmap.fromImage(qImg)
        self.label.setPixmap(pixmap)

if __name__ == "__main__":
    
    import sys
    # Create a new QApplication object
    app = QApplication(sys.argv)

    New_menu = TimeIn()
    New_menu.show() 

    sys.exit(app.exec_())
