# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'TimeIn.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import cv2

from PyQt5.QtWidgets import QWidget, QVBoxLayout, QGridLayout, QPushButton, QLineEdit
from PyQt5.QtWidgets import *
from PyQt5 import QtCore, QtGui, QtWidgets


class TimeIn(QtWidgets.QFrame):
    
    def __init__(self):
        super().__init__()
        
        self.setObjectName("Time In")
        self.resize(928, 565)
        
        # set up facial detection 
        self.face_detector = cv2.CascadeClassifier(cv2.data.haarcascades + 'haarcascade_frontalface_default.xml')
        
        
        self.widget = QtWidgets.QWidget(self)
        self.widget.setGeometry(QtCore.QRect(0, 0, 1031, 571))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.widget.setFont(font)
        self.widget.setStyleSheet("background-color: #faf4f4")
        self.widget.setObjectName("widget")
        
        # Video
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(30, 20, 581, 521))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(24)
        self.label.setFont(font)
        self.label.setCursor(QtGui.QCursor(QtCore.Qt.ForbiddenCursor))
        self.label.setStyleSheet("border:2px solid #1a1313;\n"
"border-radius : 30%;\n"
"color: #1a1313;")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        
        # Register Button
        self.pushButton = QtWidgets.QPushButton(self.widget)
        self.pushButton.setGeometry(QtCore.QRect(660, 220, 221, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.pushButton.setFont(font)
        self.pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton.setStyleSheet("border-radius: 20%;\n"
"border: 2px solid #1a1313;")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Images/icon-register.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon)
        self.pushButton.setIconSize(QtCore.QSize(32, 32))
        self.pushButton.setFlat(True)
        self.pushButton.setObjectName("pushButton")
        
        # Switch Camera
        self.pushButton_2 = QtWidgets.QPushButton(self.widget)
        self.pushButton_2.setGeometry(QtCore.QRect(660, 290, 221, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_2.setStyleSheet("QPushButton {\n"
"    background: #1a1313;\n"
"border-radius: 20%;\n"
"   color: #faf4f4;\n"
"\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #1a1313;\n"
"}")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("Images/icon-switch-white.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_2.setIcon(icon1)
        self.pushButton_2.setIconSize(QtCore.QSize(32, 32))
        self.pushButton_2.setFlat(True)
        self.pushButton_2.setObjectName("pushButton_2")
        
        # to start video streaming
        self.videoStream = cv2.VideoCapture(0)
        self.videoStream.set(4, 1080)
        
        self.timer = QtCore.QTimer(self)
        self.timer.timeout.connect(self.videoStreaming)
        self.timer.start(30)

        self.retranslateUi()
        QtCore.QMetaObject.connectSlotsByName(self)
        
    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("Frame", ""))
        self.pushButton.setText(_translate("Frame", "register"))
        self.pushButton_2.setText(_translate("Frame", "switch"))
        self.label.setText(_translate("Frame", "Loading"))
        
        
        # event function
        self.pushButton.clicked.connect(self.register)

    def videoStreaming(self):
        ret, frame = self.videoStream.read()
        
        # if no detected frames
        if not ret:
            self.label.setText("Please wait camera is loading")
            return
        
        frame = cv2.flip(frame, 1)
        
        gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
                
        # load facial detection
        faces = self.face_detector.detectMultiScale(gray,
                                                    scaleFactor=1.1,
                                                    minNeighbors=20,
                                                    minSize=(180, 180),
                                                    flags=cv2.CASCADE_SCALE_IMAGE)
        
        for (x, y, w, h) in faces:      
            cv2.rectangle(frame, (x, y), (x+w, y+h), (0,255,0), 2)
        
        # display the frame on the label
        height, width, channel = frame.shape
        bytesPerLine = channel * width
        qImg = QtGui.QImage(frame.data, width, height, bytesPerLine, QtGui.QImage.Format_BGR888)
        pixmap = QtGui.QPixmap.fromImage(qImg)
        self.label.setPixmap(pixmap)

    # open register
    def register(self):
        from Register import Register
        
        self.videoStream.release()
        cv2.destroyAllWindows()
        
        Register = Register(self)
        Register.show()
        

if __name__ == "__main__":
    
    import sys
    # Create a new QApplication object
    app = QApplication(sys.argv)

    New_menu = TimeIn()
    New_menu.show() 

    sys.exit(app.exec_())
